name: Shell Command

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Wrold"
      - name: multiple script
        run: |
          node -v
          npm -v
